### ISSUE TITLE
Solution Design API

### ISSUE THREAD

**Issue by oahmed-OS** [ShoppingTogether/ShoppingTogether.API#4]

**Comment by oahmed-OS** [comment]
Initial thoughts:

Actions:
- add user
- get user

- add item to cart
- remove item from cart
- update item to cart (upsert)
- purchase cart

- mark line paid

Rest endpoints:
GET /users
GET /users/id
POST /users

GET /cart --get active cart
POST /cart --update active cart
DELETE /cart --delete from cart

GET /receipts --paging old carts

POST /payment --mark user paid for specific cart


Note: 
- payment should not be on order line? it should be per cart per user

**Comment by kyukibug** [comment]
Initial thoughts:

Actions:

- Add User
-  Get User
-  Add Product to Cart
-  Remove product from cart
-  Mark cart as purchased
-  Mark user as paid per cart

**Comment by oahmed-OS** [comment]
Rest List:
GET /users
GET /users/id
POST /users

GET /cart --get active cart
POST /cart --update active cart
POST /cart/purchase --purchase cart
DELETE /cart --delete from cart

GET /receipts --paging old carts
POST /receipts/pay --paging old carts

**Comment by oahmed-OS** [comment]
agreed upon initial list and marking as closed for now
